#!/bin/bash
# stolen from http://blog.smalleycreative.com/tutorials/using-git-and-github-to-manage-your-dotfiles/
# This script creates symlinks from the home directory to any desired dotfiles in $dir
# places old files in $olddir as backup

# Todos
# [ ] fix repeated use. Don't move previously added symlinks to ~ too
# [ ] get files from /src with $(ls)

dir=~/dotfiles
olddir=~/dotfiles_old
files=".vimrc .gitconfig .tmux.conf"

# create dotfiles_old in homedir
echo "Creating $olddir for backup of any existing dotfiles in ~"
mkdir -pv $olddir
echo "done"

# change to the dotfiles directory
echo "Changing to the $dir directory"
cd $dir
echo "...done"

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks
for file in $files; do
  echo "Moving any existing dotfiles from ~ to $olddir"
  mv -v ~/$file ~/dotfiles_old/
  echo "Creating symlink to $file in ~"
  ln -sv $dir/$file ~/$file
done
